# vaultwright Homebrew formula.
#
# This repo doubles as its own tap. Install with:
#   brew tap alexey-lapin/vaultwright https://github.com/alexey-lapin/vaultwright
#   brew install vaultwright
#
# AUTO-GENERATED by scripts/update-formula.sh on each release — edit that script,
# not this file. The release workflow regenerates and commits it for every tag.
class Vaultwright < Formula
  desc "Build an encrypted, embedded static-file server from a single binary"
  homepage "https://github.com/alexey-lapin/vaultwright"
  version "0.0.2"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/alexey-lapin/vaultwright/releases/download/v0.0.2/vaultwright-darwin-arm64"
      sha256 "178eeb46557e5ba32f9e104e8867eca339e47e2ad3e8b93fe3c29af0cb7ef2c6"
    end
    on_intel do
      url "https://github.com/alexey-lapin/vaultwright/releases/download/v0.0.2/vaultwright-darwin-amd64"
      sha256 "fc4231cabe29c9dfccb04c646720320cd85c8b7b6c33103719a3ed25c12c8d39"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/alexey-lapin/vaultwright/releases/download/v0.0.2/vaultwright-linux-arm64"
      sha256 "57d248b71c7e429bcda25ff5e083fa1b22cba53dbff886a18bfd519dfc845964"
    end
    on_intel do
      url "https://github.com/alexey-lapin/vaultwright/releases/download/v0.0.2/vaultwright-linux-amd64"
      sha256 "c31e0ed46327adcf3213eb4e5b043a88ffe223cbed1218073649a280198c791b"
    end
  end

  def install
    # The release asset is a bare binary named vaultwright-<os>-<arch>; install it
    # under the canonical name.
    bin.install Dir["vaultwright-*"].first => "vaultwright"
  end

  test do
    assert_match "vaultwright", shell_output("#{bin}/vaultwright version")
  end
end
