# vaultwright Homebrew formula.
#
# This repo doubles as its own tap. Install with:
#   brew tap alexey-lapin/vaultwright https://github.com/alexey-lapin/vaultwright
#   brew install vaultwright
#
# AUTO-GENERATED by scripts/update-formula.sh on each release — edit that script,
# not this file. The release workflow regenerates and commits it for every tag.
class Vaultwright < Formula
  desc "Build an encrypted, embedded static-file server from a single binary"
  homepage "https://github.com/alexey-lapin/vaultwright"
  version "0.0.3"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/alexey-lapin/vaultwright/releases/download/v0.0.3/vaultwright-darwin-arm64"
      sha256 "8cee95286e393aa9747445d4310844d8b6f1da9e2e618fb8c4562c4ffe11c5aa"
    end
    on_intel do
      url "https://github.com/alexey-lapin/vaultwright/releases/download/v0.0.3/vaultwright-darwin-amd64"
      sha256 "77d8f5825c24eecdb9e273f26a8fd24a61fbc1f4202a40e398a57efe042a25c6"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/alexey-lapin/vaultwright/releases/download/v0.0.3/vaultwright-linux-arm64"
      sha256 "b1c1df46abe58eccdf9d98ef2f855d2e2d24acec9eae6c3202ec630fa609953c"
    end
    on_intel do
      url "https://github.com/alexey-lapin/vaultwright/releases/download/v0.0.3/vaultwright-linux-amd64"
      sha256 "4cbc0a37341940c009a85a4342a7cee0a9aae87261431b4f30ae77d2e23cda2d"
    end
  end

  def install
    # The release asset is a bare binary named vaultwright-<os>-<arch>; install it
    # under the canonical name.
    bin.install Dir["vaultwright-*"].first => "vaultwright"
  end

  test do
    assert_match "vaultwright", shell_output("#{bin}/vaultwright version")
  end
end
