# vaultwright Homebrew formula.
#
# This repo doubles as its own tap. Install with:
#   brew tap alexey-lapin/vaultwright https://github.com/alexey-lapin/vaultwright
#   brew install vaultwright
#
# AUTO-GENERATED by scripts/update-formula.sh on each release — edit that script,
# not this file. The release workflow regenerates and commits it for every tag.
class Vaultwright < Formula
  desc "Build an encrypted, embedded static-file server from a single binary"
  homepage "https://github.com/alexey-lapin/vaultwright"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/alexey-lapin/vaultwright/releases/download/v0.0.1/vaultwright-darwin-arm64"
      sha256 "395e01c8acf5f085cfbb33cb9d447ea725d33f65f019c07b71175f09907df71f"
    end
    on_intel do
      url "https://github.com/alexey-lapin/vaultwright/releases/download/v0.0.1/vaultwright-darwin-amd64"
      sha256 "abb10946807ce1dcc474126868a19471b899b1f6848a3061f8b3716ad6cf371e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/alexey-lapin/vaultwright/releases/download/v0.0.1/vaultwright-linux-arm64"
      sha256 "4b59b7ed2a256ba121007b92c628868787faa88f8780658c0c01397c3b90774f"
    end
    on_intel do
      url "https://github.com/alexey-lapin/vaultwright/releases/download/v0.0.1/vaultwright-linux-amd64"
      sha256 "0859ea8fe2cba5bd7a37da00a8c0c7b2add993aa512b8aef84c232b77a1ce67a"
    end
  end

  def install
    # The release asset is a bare binary named vaultwright-<os>-<arch>; install it
    # under the canonical name.
    bin.install Dir["vaultwright-*"].first => "vaultwright"
  end

  test do
    assert_match "vaultwright", shell_output("#{bin}/vaultwright version")
  end
end
