#!/usr/bin/env bash
# Regenerate Formula/vaultwright.rb for a release: pin the version, URLs, and per-arch
# SHA-256 of the CLI binaries in dist/. Run after scripts/build-release.sh.
#
#   VERSION=v1.2.3 ./scripts/update-formula.sh
#
# Windows is intentionally omitted (no Homebrew). The release workflow runs this and
# commits the result to main so the tap tracks the latest release.
set -euo pipefail
cd "$(dirname "$0")/.."

VERSION=${VERSION:?set VERSION to the release tag, e.g. v1.2.3}
REPO=${REPO:-alexey-lapin/vaultwright}
OUT=${OUT:-dist}
ver=${VERSION#v} # formula `version` is unprefixed

sha256() { if command -v sha256sum >/dev/null 2>&1; then sha256sum "$1"; else shasum -a 256 "$1"; fi | awk '{print $1}'; }

# Map Homebrew (os, cpu) blocks to the dist asset for that target.
asset() { echo "$OUT/vaultwright-$1-$2"; }
url()   { echo "https://github.com/$REPO/releases/download/$VERSION/vaultwright-$1-$2"; }

for f in darwin-arm64 darwin-amd64 linux-arm64 linux-amd64; do
  test -f "$(asset "${f%-*}" "${f#*-}")" || { echo "missing $(asset "${f%-*}" "${f#*-}") — run scripts/build-release.sh first" >&2; exit 1; }
done

mkdir -p Formula
cat > Formula/vaultwright.rb <<EOF
# vaultwright Homebrew formula.
#
# This repo doubles as its own tap. Install with:
#   brew tap $REPO https://github.com/$REPO
#   brew install vaultwright
#
# AUTO-GENERATED by scripts/update-formula.sh on each release — edit that script,
# not this file. The release workflow regenerates and commits it for every tag.
class Vaultwright < Formula
  desc "Build an encrypted, embedded static-file server from a single binary"
  homepage "https://github.com/$REPO"
  version "$ver"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "$(url darwin arm64)"
      sha256 "$(sha256 "$(asset darwin arm64)")"
    end
    on_intel do
      url "$(url darwin amd64)"
      sha256 "$(sha256 "$(asset darwin amd64)")"
    end
  end

  on_linux do
    on_arm do
      url "$(url linux arm64)"
      sha256 "$(sha256 "$(asset linux arm64)")"
    end
    on_intel do
      url "$(url linux amd64)"
      sha256 "$(sha256 "$(asset linux amd64)")"
    end
  end

  def install
    # The release asset is a bare binary named vaultwright-<os>-<arch>; install it
    # under the canonical name.
    bin.install Dir["vaultwright-*"].first => "vaultwright"
  end

  test do
    assert_match "vaultwright", shell_output("#{bin}/vaultwright version")
  end
end
EOF
echo "wrote Formula/vaultwright.rb for $VERSION"
